version: '3'

networks:
  myrabbitmq:
    name: myrabbitmq
    driver: bridge

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
      - RABBITMQ_ERLANG_COOKIE=SUPER1SECRET1COOKIE
      - RABBITMQ_NODENAME=master
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
    networks:
      - myrabbitmq
